name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  actions: read  
  id-token: write # For OIDC to Azure

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_adf_dev:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Download ADF artifact
        uses: actions/download-artifact@v4
        with:
          name: adf-arm-template
          github-token: ${{ secrets.GITHUB_TOKEN }} # auth for cross-run download
          run-id: ${{ github.event.workflow_run.id }} # the CI run that triggered this

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          # This requires OIDC to be configured between GitHub and Azure
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ADF content
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.RESOURCE_GROUP }}
          template: ARMTemplateForFactory.json
          parameters: ARMTemplateParametersForFactory.json factoryName=adf-${{ vars.RESOURCE_GROUP }}
