name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev
    paths:
      - 'platform/adf/**'
      - '.github/workflows/ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - run: echo "Hello, world!"
